### ISSUE TITLE
More information at readme

### ISSUE THREAD

**Issue by zonky2** [oveleon/contao-advanced-form-login-bundle#1]
Please explain what is "advanced" at your login.

**Comment by eki89** [comment]
Hello zonky2,
it's an extention for our advanced form bundle. With the advanced form bundle you are able to create multipage forms and this extension extends the advanced form by the possibility to login or create a member on a multipage form.
But yes, i will add a description to the bundle. My extionsion is useless for the community if nobody knows what to do.

**Comment by zoglo** [comment]
The main bundle for this has been archived and this bundle won't be supported anymore.
